apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: ${NAMESPACE}
data:
  url: https://${HOST}
  dex.config: |
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: ${LDAP_HOST}
        insecureNoSSL: false
        bindDN: ${LDAP_BIND_DN}
        bindPW: ${LDAP_BIND_PW}
        userSearch:
          baseDN: ${LDAP_BASE_DN}
          filter: "(objectClass=person)"
          username: sAMAccountName
          idAttr: DN
          emailAttr: mail
          nameAttr: cn